In [ ]:
import csv
import numpy as np
import pandas as pd

with open("/content/drive/MyDrive/Colab Notebooks/CSCI_544_DATA/all.csv", 'r') as file:
  csvreader = csv.reader(file)
  question_list = []
  answer_list = []
  for row in csvreader:
    question_list.append(row[0].lower())
    answer_list.append(row[1])
    
crypto_df = pd.DataFrame()
crypto_df['question'] = question_list
crypto_df['answer'] = answer_list
copy_question_list = question_list.copy()

crypto_df

question  \
0      What is the best crypto wallet between Coinbas...   
1                                 Is Binance trustworthy   
2                  How do I create an account on Binance   
3      Which is a better exchange for Indians to trad...   
4       What are the best coins to invest in binance com   
...                                                  ...   
16831  Whats your opinion about the future of cryptoc...   
16832  What is a good exchange platform to buy Ripple...   
16833  I am investing 70 of my whole savings in BTC a...   
16834  Do you think BAT can break into the top 10 in ...   
16835  Is XRP a good long term investment and is 2022...   

                                                  answer  
0      Binance and Coinbase are two cryptocurrency pl...  
1      Binance is the world's largest cryptocurrency ...  
2      Binance is still the largest crypto-to-crypto ...  
3      Running a cryptocurrency business in India is ...  
4      You can try to have a look on lumi coin, peopl...  
...                                                  ...  
16831  I am going to try to make it as simple as poss...  
16832  Ah yes, Ripple (XRP) [1] - the most divisive c...  
16833  Since Bitcoin made waves in 2017 for hitting a...  
16834  The answer is yes to both. The price is a simp...  
16835  Do you know Warren Buffett's number one rule o...  

[16836 rows x 2 columns]

### BERT

In [ ]:
!pip install sentence_transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 1.9 MB/s 
     |████████████████████████████████| 5.5 MB 30.5 MB/s 
     |████████████████████████████████| 1.3 MB 74.0 MB/s 
     |████████████████████████████████| 182 kB 83.0 MB/s 
     |████████████████████████████████| 7.6 MB 73.4 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=2f87ec604a654897fa6d3ef9c289fd6528337cb69fa808880cc91292df43678c
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [ ]:
import random
import torch
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# model = SentenceTransformer('bert-base-nli-mean-tokens')
bert_model = SentenceTransformer('sentence-transformers/distilbert-base-nli-max-tokens')
sentence_embeddings = bert_model.encode(question_list)

user_ask = input()

test_sentence = bert_model.encode([user_ask])

index = np.argmax(cosine_similarity(test_sentence,sentence_embeddings))

print(index)
print(answer_list[index])

how the price of bitcoin is affecting bitcoin cash and etherium
2001
To abuse an oft quoted phrase, the impact of the coronavirus SARS-CoV2 (which causes COVID90) has not been price in.  Supply chains from Asian markets to the Western consumers has been seriously affected but the impact (like a deep sea earthquake) is a distant swell yet to hit landfall.  I'm expecting the financial impact of government shutdown of factories to occur in 2\u20133 months, when delays and shortages push wholesale prices through the roof.  This may cause a significant correction in the stock markets worldwide, which in the short term may cause a dip in BTC price. If this occurs around May '20 (halving), there may be a steep correction.  But as was noted during the US assassination of Soleimani in January, BTC price rallied after the event, despite global fears of the act triggering another regional war.  


In [ ]:
question1 = bert_model.encode(['how do people send crypto from a trust wallet to binance'])
question2 = bert_model.encode(['how to send cyrto to binance from trust wallet'])
cosine_similarity(question2,question1)

array([[0.92691106]], dtype=float32)

In [ ]:
question1 = bert_model.encode(['how the price of bitcoin is affecting bitcoin cash and etherium'])
question2 = bert_model.encode(['how etherium and bitcoin cash prices are impacted by the price of bitcoin'])
cosine_similarity(question2,question1)

array([[0.9637321]], dtype=float32)

In [ ]:
question1 = bert_model.encode(['how do i create an account on binance'])
question2 = bert_model.encode(['how to create account in binance'])
cosine_similarity(question2,question1)

array([[0.9590881]], dtype=float32)

In [ ]:
# with open("/content/drive/MyDrive/Colab Notebooks/CSCI_544_DATA/Junlin.csv", 'r') as file:
#   csvreader = csv.reader(file)
#   test_question_list = []
#   test_index_list = []
#   for row in csvreader:
#     test_question_list.append(row[0])
#     test_index_list.append(row[1])

# test_question_list = test_question_list[1:201]
# test_index_list = test_index_list[1:201]

with open("/content/drive/MyDrive/Colab Notebooks/CSCI_544_DATA/Anushka.csv", 'r') as file:
  csvreader = csv.reader(file)
  test_question_list = []
  test_index_list = []
  for row in csvreader:
    test_question_list.append(row[1])
    test_index_list.append(row[0])

with open("/content/drive/MyDrive/Colab Notebooks/CSCI_544_DATA/Kai.csv", 'r') as file:
  csvreader = csv.reader(file)
  for row in csvreader:
    test_question_list.append(row[1])
    test_index_list.append(row[0])

with open("/content/drive/MyDrive/Colab Notebooks/CSCI_544_DATA/Joohan_revised.csv", 'r') as file:
  csvreader = csv.reader(file)
  for row in csvreader:
    test_question_list.append(row[1])
    test_index_list.append(row[0])

with open("/content/drive/MyDrive/Colab Notebooks/CSCI_544_DATA/Behzad_changed.csv", 'r') as file:
  csvreader = csv.reader(file)
  for row in csvreader:
    test_question_list.append(row[1])
    test_index_list.append(row[0])

# test_question_list = test_question_list[1:]
# test_index_list = test_index_list[1:]

count = 0
low_sim = 0
for i in range(len(test_question_list)):
  test_sentence = bert_model.encode([test_question_list[i]])
  similaritu_list = cosine_similarity(test_sentence,sentence_embeddings)
  index = np.argmax(similaritu_list)
  if similaritu_list[0][index] <= 0.8:
    low_sim += 1
  else:
    if str(index) == test_index_list[i]:
      count +=1

accuracy = count/len(test_question_list)
print(f'BERT model accuracy is:',accuracy)

BERT model accuracy is: 0.8308605341246291


In [ ]:
cos_sum = 0
for i in range(len(test_index_list)):
  cos_sum += cosine_similarity(bert_model.encode([test_question_list[i]]), bert_model.encode([question_list[i]]))

average_sim = cos_sum/len(test_index_list)
print(f'average_similarity is:', average_sim)

average_similarity is: [[0.6040147]]


### TF_IDF

In [ ]:
!pip install contractions
import re
import contractions
import nltk
from nltk.corpus import stopwords
nltk.download('all')
from nltk.stem import WordNetLemmatizer

def remove_HTML_URL(text): # function to remove HTML/URL symbol
    text = re.sub(r'^https?:\/\/.*[\r\n]*', '', text, flags=re.MULTILINE)
    text = re.sub('<.*?>+', '', text)
    return text
  
def remove_extra_spaces(text): # function to remove the extra space
    res = " ".join(text.split())
    return res
  
def perform_contractions(text): # perform contractions on the reviews
    list1 = []
    for word in text.split():
        list1.append(contractions.fix(word))
    return " ".join(list1)

def remove_stop_words(text): # remove the stopd words
    stop_words= stopwords.words('english') # get all stop words
    list1 = []
    for word in text.split():
        if word not in stop_words: # remove the stop wrods from text
            list1.append(word) 
    return ' '.join(list1)

def perform_lemmatization(text): # perform lemmatization
    lemmatizer = WordNetLemmatizer()
    list1 = []
    for word in text.split():
        word = lemmatizer.lemmatize(word) # lemmatization
        list1.append(word)
    return ' '.join(list1)

crypto_df['question'] = crypto_df['question'].apply(lambda x: x.lower())
crypto_df['question'] = crypto_df['question'].apply(lambda x: remove_HTML_URL(x))
crypto_df['question'] = crypto_df['question'].apply(lambda x: remove_extra_spaces(x))
crypto_df['question'] = crypto_df['question'].apply(lambda x: perform_contractions(x))
crypto_df['question'] = crypto_df['question'].apply(lambda x: remove_stop_words(x))
crypto_df['question'] = crypto_df['question'].apply(lambda x: perform_lemmatization(x))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 106 kB 4.9 MB/s 
     |████████████████████████████████| 287 kB 32.1 MB/s 


[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloadin

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

user_ask = input()
user_ask = remove_HTML_URL(user_ask)
user_ask = remove_extra_spaces(user_ask)
user_ask = perform_contractions(user_ask)
user_ask = remove_stop_words(user_ask)
user_ask = perform_lemmatization(user_ask)

question_list = crypto_df['question'].to_list()
question_list.append(user_ask)
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(question_list)

max_sim = 0
index_num = 0
index_list = []
for i in range(X.shape[0]-1):
  cos_sim = cosine_similarity(X[i],X[X.shape[0]-1])
  if cos_sim > 0.85:
    index_list.append(i)
    if cos_sim > max_sim:
      max_sim = cos_sim
      index_num = i

if len(index_list) == 0:
  print('there is no similar sentence')
else:
  print(copy_question_list[index_num])

how to send cyrto to binance from trust wallet
there is no similar sentence


In [ ]:
cosine_similarity(X[81],X[X.shape[0]-1]) 

array([[0.60950305]])

In [ ]:
question_list[2]

'create account binance'

In [ ]:
user_ask = 'how etherium and bitcoin cash prices are impacted by the price of bitcoin'
user_ask = remove_extra_spaces(user_ask)
user_ask = perform_contractions(user_ask)
user_ask = remove_stop_words(user_ask)
user_ask = perform_lemmatization(user_ask)

question_list = crypto_df['question'].to_list()
question_list.append(user_ask)
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(question_list)

cosine_similarity(X[2001],X[X.shape[0]-1]) 

array([[0.58844276]])

In [ ]:
user_ask = 'how to create account in binance'
user_ask = remove_extra_spaces(user_ask)
user_ask = perform_contractions(user_ask)
user_ask = remove_stop_words(user_ask)
user_ask = perform_lemmatization(user_ask)

question_list = crypto_df['question'].to_list()
question_list.append(user_ask)
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(question_list)

cosine_similarity(X[2],X[X.shape[0]-1]) 

array([[1.]])

### Word2Vec

In [ ]:
import gensim

s1 = 'how do people send crypto from a trust wallet to binance'
s2 = 'how to send cyrto to binance from trust wallet'

word2vec_model = gensim.models.Word2Vec(question_list, size=300, window=11, min_count=1, sg=0, workers=8)

distance = word2vec_model.wmdistance(s1, s2)
distance

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: DeprecationWarning: Call to deprecated `wmdistance` (Method will be removed in 4.0.0, use self.wv.wmdistance() instead).


0.6887152044360692

In [ ]:
s1 = 'how the price of bitcoin is affecting bitcoin cash and etherium'
s2 = 'how etherium and bitcoin cash prices are impacted by the price of bitcoin'

word2vec_model = gensim.models.Word2Vec(question_list, size=300, window=11, min_count=1, sg=0, workers=8)

distance = word2vec_model.wmdistance(s1, s2)
distance

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wmdistance` (Method will be removed in 4.0.0, use self.wv.wmdistance() instead).


0.6002937671069377

In [ ]:
s1 = 'how do i create an account on binance'
s2 = 'how to create account in binance'

word2vec_model = gensim.models.Word2Vec(question_list, size=300, window=11, min_count=1, sg=0, workers=8)

distance = word2vec_model.wmdistance(s1, s2)
distance

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: DeprecationWarning: Call to deprecated `wmdistance` (Method will be removed in 4.0.0, use self.wv.wmdistance() instead).


0.6222951044540477